version: "3.8"
services:
  backend:
    ports:
      - "5000:5000"
    build: ./backend
    command: gunicorn -c "python:config.gunicorn" --reload "manage:app"
    volumes:
      - ./backend:/home/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:5000/health}"
      interval: "90s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
  db:
    image: "postgres:13-alpine"
    env_file:
      - ./.env.dev
    volumes:
      - "postgres_dev:/var/lib/postgresql/data"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

volumes:
  postgres_dev:
